### ISSUE TITLE
Remove default "@returns" for constructors

### ISSUE THREAD

**Issue by VoidVolker** [kimlimjustin/vscode-jsdoc-generator#3]
By default constructor returns and current class instance. If constructor returns any value - add docs.

**Comment by kimlimjustin** [comment]
I don't think this is possible to detect whether a function is a constructor except by creating an intellisense, but I want to keep this extension lightweight. However, I'll just detect if the line contains the word `constructor` and if it is, I'll just remove the default "@returns".

However, if you get any ideas, any PR will be welcomed :)
