### ISSUE TITLE
Generate JSDoc does not work when the function is on the first line of the file

### ISSUE THREAD

**Issue by amadorgabriel** [kimlimjustin/vscode-jsdoc-generator#5]
When I run ctrl + shift + p and my function is on the first line of code, the error is raised:

![image](https://user-images.githubusercontent.com/48362368/134165244-b5e9b1bb-2cf7-4198-aedb-bee9bee006d0.png)

but if I run on line two, everything works normally. 😄

**Comment by kimlimjustin** [comment]
Thanks for your report, will look into soon

**Comment by kimlimjustin** [comment]
Committed a fix for this, a new version with the bug fixes will be released soon, stay tuned!

**Comment by kimlimjustin** [comment]
Published v0.0.3, give it a try!

**Comment by amadorgabriel** [comment]
Worked, thank you! 🎉
